"""Update schema

Revision ID: 1c37d5254da6
Revises: tiktok_integration_001
Create Date: 2026-03-13 21:15:39.474699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c37d5254da6'
down_revision: Union[str, None] = 'tiktok_integration_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('video_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'campaigns', 'video_generations', ['video_id'], ['id'], ondelete='SET NULL')
    op.add_column('video_generations', sa.Column('is_public', sa.Integer(), nullable=True))
    op.add_column('video_generations', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_generations', 'title')
    op.drop_column('video_generations', 'is_public')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'video_id')
    # ### end Alembic commands ###
