"""Add audience targeting model

Revision ID: 95f4fd4ff52f
Revises: d5896a814be5
Create Date: 2026-01-18 19:18:22.113544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f4fd4ff52f'
down_revision: Union[str, None] = 'd5896a814be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audience_targets',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('countries', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('regions', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('cities', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('genders', sa.ARRAY(sa.String()), server_default='{"ALL"}', nullable=False),
    sa.Column('interests', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('languages', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('devices', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audience_targets_campaign_id'), 'audience_targets', ['campaign_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audience_targets_campaign_id'), table_name='audience_targets')
    op.drop_table('audience_targets')
    # ### end Alembic commands ###
