"""Add lat lng and city to campaign

Revision ID: ae6521012c1e
Revises: 1c37d5254da6
Create Date: 2026-03-14 11:10:10.846262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6521012c1e'
down_revision: Union[str, None] = '1c37d5254da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('lat', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('campaigns', sa.Column('lng', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('campaigns', sa.Column('city', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'city')
    op.drop_column('campaigns', 'lng')
    op.drop_column('campaigns', 'lat')
    # ### end Alembic commands ###
