"""Add video_generations table

Revision ID: d5896a814be5
Revises: 0be2c248e356
Create Date: 2026-01-18 09:43:52.383786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5896a814be5'
down_revision: Union[str, None] = '0be2c248e356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_generations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('duration', sa.Enum('SHORT', 'LONG', name='videoduration'), nullable=False),
    sa.Column('quality', sa.Enum('STANDARD', 'PROFESSIONAL', name='videoquality'), nullable=False),
    sa.Column('kling_task_id', sa.String(length=255), nullable=True),
    sa.Column('kling_status', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'UPLOADING', 'COMPLETED', 'FAILED', name='videostatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('video_url', sa.String(length=1024), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('s3_key', sa.String(length=512), nullable=True),
    sa.Column('s3_thumbnail_key', sa.String(length=512), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('tokens_spent', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_generations_campaign_id'), 'video_generations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_video_generations_kling_task_id'), 'video_generations', ['kling_task_id'], unique=False)
    op.create_index(op.f('ix_video_generations_status'), 'video_generations', ['status'], unique=False)
    op.create_index(op.f('ix_video_generations_user_id'), 'video_generations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_generations_user_id'), table_name='video_generations')
    op.drop_index(op.f('ix_video_generations_status'), table_name='video_generations')
    op.drop_index(op.f('ix_video_generations_kling_task_id'), table_name='video_generations')
    op.drop_index(op.f('ix_video_generations_campaign_id'), table_name='video_generations')
    op.drop_table('video_generations')
    # ### end Alembic commands ###
