"""create_campaigns_table

Revision ID: eab37e25c934
Revises: 001
Create Date: 2026-01-17 13:30:34.694764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab37e25c934'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('product_desc', sa.Text(), nullable=True),
    sa.Column('ai_script', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tokens_spent', sa.Integer(), nullable=False),
    sa.Column('target_audience_id', sa.UUID(), nullable=True),
    sa.Column('tiktok_ad_id', sa.String(length=100), nullable=True),
    sa.Column('tiktok_campaign_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_user_id'), 'campaigns', ['user_id'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_index(op.f('ix_campaigns_user_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
